# Generated by Django 4.2.23 on 2025-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0002_attirebase_user_ceremoniesbase_user_cuisinebase_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attirebase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ceremoniesbase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cuisinebase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='historybase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
    ]
