# Generated by Django 4.2.23 on 2025-09-26 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0005_entry_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='favorite_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
