# Generated by Django 4.2.23 on 2025-09-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0006_alter_entry_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='commonly',
            field=models.CharField(default='pop', max_length=50),
            preserve_default=False,
        ),
    ]
