# Generated by Django 4.2.23 on 2025-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0007_entry_commonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attirebase',
            name='extract',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='ceremoniesbase',
            name='extract',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='cuisinebase',
            name='extract',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='entry',
            name='commonly',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='extract',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isipedi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isixhosa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isizulu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='word_usage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historybase',
            name='extract',
            field=models.TextField(blank=True, max_length=7000000),
        ),
        migrations.AlterField(
            model_name='quizbase',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizbase',
            name='question',
            field=models.CharField(max_length=900),
        ),
    ]
