# Generated by Django 4.2.23 on 2025-09-29 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0008_alter_attirebase_extract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='english',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='extract',
            field=models.CharField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isipedi',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isixhosa',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='isizulu',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='QuizScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
