# Generated by Django 4.2.23 on 2025-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0009_alter_entry_english_alter_entry_extract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='word',
            field=models.IntegerField(default=0),
        ),
    ]
